#!/bin/bash

echo "Testing token counter in the UI..."
echo ""
echo "1. Go to http://localhost:3001/workspace/text-creation"
echo "2. Type a simple message like 'What is 2+2?'"
echo "3. Submit and wait for the response"
echo "4. Check the token counter in the input area"
echo ""
echo "Expected behavior:"
echo "- Initially shows: 0.0% 0 / [context_length] tokens"
echo "- After response: Should show actual token usage"
echo ""
echo "The context_length varies by model:"
echo "- GPT-OSS-20b: Usually 4096 or 8192"
echo "- Llama models: Usually 4096-8192"
echo "- Tongyi-DeepResearch: Usually 32000+"
echo ""
echo "If still showing 0 / 128000, the Context component might not have updated."
echo "Try refreshing the page."